id: ABD33425F
title: 'Illuminating the Meaning of Empowerment: A Self-Initiation for the Female
  Practice of the Ḍākinī'
type: translation
pechas:
- I8F23C5D4
- I3677E95F
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:41:28.491949
  last_modified_at: 2023-01-04 12:41:28.491969
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I8F23C5D4/EEE2: 8D6B
  I3677E95F/4B3E: 8D6B
